# Generated by Django 5.2.17 on 2026-09-24 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChargingStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('contact', models.CharField(max_length=30)),
                ('operating_hours', models.CharField(default='24/7 (Always Open)', max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('TEMPORARILY_CLOSED', 'Temporarily Closed'), ('MAINTENANCE', 'Under Maintenance')], default='ACTIVE', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChargingPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_number', models.CharField(max_length=50)),
                ('connector_type', models.CharField(choices=[('CCS2', 'CCS-2 (DC Fast)'), ('TYPE2', 'Type 2 (AC Normal)'), ('CHADEMO', 'CHAdeMO (DC)'), ('GBT', 'GB/T (DC Fast)')], default='CCS2', max_length=20)),
                ('power_rating', models.DecimalField(decimal_places=2, help_text='Power rating in kW (e.g. 50.0)', max_digits=6)),
                ('charging_speed', models.CharField(choices=[('STANDARD_AC', 'Standard AC (7 - 22 kW)'), ('FAST_DC', 'Fast DC (30 - 60 kW)'), ('RAPID_DC', 'Rapid DC (60 - 150 kW)')], default='FAST_DC', max_length=20)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('CHARGING', 'Charging'), ('FINISHING', 'Finishing'), ('OUT_OF_SERVICE', 'Out of Service')], default='AVAILABLE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='stations.chargingstation')),
            ],
            options={
                'ordering': ['station', 'point_number'],
                'unique_together': {('station', 'point_number')},
            },
        ),
    ]
