# Generated by Django 5.2.17 on 2026-09-24 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress (Charging)'), ('FINISHING', 'Finishing'), ('COMPLETED', 'Completed')], default='IN_PROGRESS', max_length=20)),
                ('initial_soc', models.PositiveIntegerField(default=25, help_text='Initial State of Charge (%)')),
                ('final_soc', models.PositiveIntegerField(default=85, help_text='Final State of Charge (%)')),
                ('energy_delivered_kwh', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('notes', models.TextField(blank=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='charging_session', to='bookings.booking')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operated_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
