# Generated by Django 5.2.17 on 2026-09-24 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_date', models.DateField()),
                ('requested_time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('preferred_connector', models.CharField(default='CCS2', max_length=30)),
                ('queue_position', models.PositiveIntegerField(default=1)),
                ('priority', models.PositiveIntegerField(default=1, help_text='Priority rank: 1 (Standard), 2 (Urgent/VIP)')),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('NOTIFIED', 'Slot Available (Notified)'), ('ASSIGNED', 'Assigned / Booked'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='WAITING', max_length=20)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='stations.chargingstation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-priority', 'created_at'],
            },
        ),
    ]
