# Generated by Django 5.2.17 on 2026-09-24 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=100)),
                ('connector_type', models.CharField(choices=[('CCS2', 'CCS-2 (DC Fast)'), ('TYPE2', 'Type 2 (AC Normal)'), ('CHADEMO', 'CHAdeMO (DC)'), ('GBT', 'GB/T (DC Fast)')], default='CCS2', max_length=20)),
                ('battery_capacity', models.DecimalField(decimal_places=2, help_text='Battery capacity in kWh', max_digits=6)),
                ('nickname', models.CharField(blank=True, max_length=60, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
